### ISSUE TITLE
DESCRIPTION: move ExperimentHub to Imports

### ISSUE THREAD

**Issue by lgeistlinger** [ccb-hms/MouseAgingData#2]
I don't think we need `ExperimentHub` in `Depends`, having it in `Imports` will be sufficient.

**Comment by tram-nguyen-n** [comment]
Currently the parabiosis10x() function uses the querying functionality from the `ExperimentHub` package, so the build failed with `ExperimentHub` in `Imports`.  Had to put it back in `Depends` for now.

**Comment by lgeistlinger** [comment]
The `query` function used in the `parabiosis10x` function is defined in the `AnnotationHub` package. Thus, we need:

1. Both `AnnotationHub` and `ExperimentHub` in `Imports` of the `DESCRIPTION` file, and
2. Refer to functionality from imported packages using the `package::function` notation inside the body of the `parabiosis10x` function, ie

[line 65 of parabiosis10x.R](https://github.com/ccb-hms/MouseAgingData/blob/ccdac1cd6b0b5688640abefa8790c76460c98641/R/parabiosis10x.R#L65) will then need to be updated to: `eh <- ExperimentHub::ExperimentHub()`, and
[line 68 of parabiosis10x.R](https://github.com/ccb-hms/MouseAgingData/blob/ccdac1cd6b0b5688640abefa8790c76460c98641/R/parabiosis10x.R#L68C5-L68C27) will then need to be updated to `eh <- AnnotationHub::query(eh, title)`.

Note that it is good practice to use the `package::function` notation for functionality imported from other packages inside your package's codebase to avoid namespace conflicts (ie a case where two or more packages define a function of the same name). This also simplifies dependency management in your roxygen comments, ie. when performing the above modifcations, we don't need to declare the import from `ExperimentHub` in [line 68 of parabiosis10x.R](https://github.com/ccb-hms/MouseAgingData/blob/ccdac1cd6b0b5688640abefa8790c76460c98641/R/parabiosis10x.R#L61).
