### ISSUE TITLE
move SingleCellExperiment to Depends

### ISSUE THREAD

**Issue by lgeistlinger** [ccb-hms/MouseAgingData#6]
I would be in favor to move `SingleCellExperiment` to `Depends` as eg the [scRNAseq](https://bioconductor.org/packages/scRNAseq) package does it. 

We would then only need:

```
library(MouseAgingData)
``` 

and users would be able to start working with the data right after calling the dataset loading function without the need for an additional

``` 
library(SingleCellExperiment)
```

Thoughts @nturaga?

**Comment by tram-nguyen-n** [comment]
Chatted with @nturaga -- putting `SingleCellExperiment` back in `Depends`.
